name: monolegal_http
description: Paquete http de monolegal
version: 0.0.2

homepage: https://www.monolegal.co/

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
