name: monolegal_http
description: Paquete http de monolegal
version: 0.0.1

homepage: https://www.monolegal.co/

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
